### ISSUE TITLE
replace after emit logic for webpack v4.29+

### ISSUE THREAD

**Issue by whollacsek** [thredup/rollbar-sourcemap-webpack-plugin#61]
Webpack v4.29.0 introduced `output.futureEmitAssets` which breaks this plugin. From the [release](https://github.com/webpack/webpack/releases/tag/v4.29.0):
> - assets are replaced with SizeOnlySources
> - reading assets after emitting is no longer allowed

https://github.com/webpack/webpack/pull/8642/files

**Comment by sslotsky** [comment]
Running into this issue as well. The stack trace:

```
/home/sam/manifold-www/node_modules/webpack/lib/Compiler.js:661
		throw this._error();
		^

Error: Content and Map of this Source is no longer available (only size() is supported)
    at SizeOnlySource._error (/home/sam/manifold-www/node_modules/webpack/lib/Compiler.js:647:10)
    at SizeOnlySource.source (/home/sam/manifold-www/node_modules/webpack/lib/Compiler.js:661:14)
    at RollbarSourceMapPlugin.uploadSourceMap (/home/sam/manifold-www/node_modules/rollbar-sourcemap-webpack-plugin/dist/RollbarSourceMapPlugin.js:180:63)
    at /home/sam/manifold-www/node_modules/async/dist/async.js:3110:16
    at eachOfArrayLike (/home/sam/manifold-www/node_modules/async/dist/async.js:1069:9)
    at eachOf (/home/sam/manifold-www/node_modules/async/dist/async.js:1117:5)
    at Object.eachLimit (/home/sam/manifold-www/node_modules/async/dist/async.js:3172:5)
    at RollbarSourceMapPlugin.uploadSourceMaps (/home/sam/manifold-www/node_modules/rollbar-sourcemap-webpack-plugin/dist/RollbarSourceMapPlugin.js:191:23)
    at RollbarSourceMapPlugin.afterEmit (/home/sam/manifold-www/node_modules/rollbar-sourcemap-webpack-plugin/dist/RollbarSourceMapPlugin.js:83:12)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/sam/manifold-www/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/home/sam/manifold-www/node_modules/tapable/lib/Hook.js:154:20)
    at asyncLib.forEachLimit.err (/home/sam/manifold-www/node_modules/webpack/lib/Compiler.js:432:27)
    at /home/sam/manifold-www/node_modules/neo-async/async.js:2813:7
    at done (/home/sam/manifold-www/node_modules/neo-async/async.js:3521:9)
    at outputFileSystem.writeFile.err (/home/sam/manifold-www/node_modules/webpack/lib/Compiler.js:400:9)
    at /home/sam/manifold-www/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
error Command failed with exit code 1.
```

Anything we can do to work around, or any suggestions for submitting a fix?

**Comment by nisargrthakkar** [comment]
Getting same error

```
var/www/html/bannerbuzz-reactjs/node_modules/webpack/lib/Compiler.js:661
throw this._error();
^
Error: Content and Map of this Source is no longer available (only size() is supported)
at SizeOnlySource._error (/var/www/html/bannerbuzz-reactjs/node_modules/webpack/lib/Compiler.js:647:10)
at SizeOnlySource.source (/var/www/html/bannerbuzz-reactjs/node_modules/webpack/lib/Compiler.js:661:14)
at RollbarSourceMapPlugin.uploadSourceMap (/var/www/html/bannerbuzz-reactjs/node_modules/rollbar-sourcemap-webpack-plugin/dist/RollbarSourceMapPlugin.js:180:63)
at /var/www/html/bannerbuzz-reactjs/node_modules/async/dist/async.js:3110:16
at eachOfArrayLike (/var/www/html/bannerbuzz-reactjs/node_modules/async/dist/async.js:1069:9)
at eachOf (/var/www/html/bannerbuzz-reactjs/node_modules/async/dist/async.js:1117:5)
at Object.eachLimit (/var/www/html/bannerbuzz-reactjs/node_modules/async/dist/async.js:3172:5)
at RollbarSourceMapPlugin.uploadSourceMaps (/var/www/html/bannerbuzz-reactjs/node_modules/rollbar-sourcemap-webpack-plugin/dist/RollbarSourceMapPlugin.js:191:23)
at RollbarSourceMapPlugin.afterEmit (/var/www/html/bannerbuzz-reactjs/node_modules/rollbar-sourcemap-webpack-plugin/dist/RollbarSourceMapPlugin.js:83:12)
at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/html/bannerbuzz-reactjs/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:7:1)
at AsyncSeriesHook.lazyCompileHook (/var/www/html/bannerbuzz-reactjs/node_modules/tapable/lib/Hook.js:154:20)
at asyncLib.forEachLimit.err (/var/www/html/bannerbuzz-reactjs/node_modules/webpack/lib/Compiler.js:432:27)
at /var/www/html/bannerbuzz-reactjs/node_modules/neo-async/async.js:2813:7
at done (/var/www/html/bannerbuzz-reactjs/node_modules/neo-async/async.js:3521:9)
at outputFileSystem.writeFile.err (/var/www/html/bannerbuzz-reactjs/node_modules/webpack/lib/Compiler.js:400:9)
at /var/www/html/bannerbuzz-reactjs/node_modules/graceful-fs/graceful-fs.js:45:10
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by nisargrthakkar** [comment]
any update on this?

**Comment by stubar** [comment]
Until this PR get's merged we can use
```config.output.futureEmitAssets  = false;```

**Comment by nisargrthakkar** [comment]
Any update on this?

**Comment by FoxxMD** [comment]
Helpful tip for anyone stumbling across this you can use [patch-package](https://github.com/ds300/patch-package) along with code changes in #64 to fix this without using `futureEmitAssets`

**Comment by brandondoran** [comment]
I will look into fixing but as I understand it, `output.futureEmitAssets` is a way to opt in to webpack v5 behavior pre release. And this is disabled by default in v4. So it seems like we have a temp workaround by just leaving this option disabled.

#64 doesn't look like the right fix. I think we can fix be taking a similar approach as in https://github.com/webpack/webpack/issues/8883

**Comment by cain** [comment]
Also getting this issue with nuxtJS, please keep us updated if a fix goes into a release :) 

Is it safe to use `output.futureEmitAssets` and will it change anything?

**Comment by mskelton** [comment]
I see that there appears to be some work being done on this recently on the rework-after-emit branch.  Any way I can help to push this across the finish line so that webpack 5 users (like me) can start using this plugin again?

**Comment by brandondoran** [comment]
@mskelton yes rework-after-emit branch was effort to add support for Webpack 4.29+ with futureEmitAssets enabled. The hope was it would just work in v5 but turns out more is needed as its seems fairly there's fairly major changes to the plugin architecture. At the time (just after v5 became "stable") there wasn't really any documentation. It seems that supporting v4 and v5 may in same version of plugin might be tricky. I'll try devote some time to this.

**Comment by mskelton** [comment]
@brandondoran Thanks for the update, let me know if I can help in any way.  FWIW html-webpack-plugin is taking the same approach of having a new major version that is just for webpack 5 and won't support webpack 4.

https://github.com/jantimon/html-webpack-plugin/issues/1527
